import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "../components/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className = "max-h-10">
      <div className="h-24">
      <div className="absolute inset-0 flex justify-center items-center z-[-10]">
        <div className="flex items-center">
          <img src="/human_1.png" alt="Medibot Logo" className="w-20 h-24" />
          <div className="text-5xl text-[#A49B9B]">Huego</div>
        </div>
      </div>
        {children}
        <div style={{position: "absolute", bottom: 4, left: "50%", transform: "translate(-50%, 0)" }}>
        <Footer/>
        </div>
        
      </div>
      
    </body>
  </html>
  );
}
