import Footer from "./footer";

const TermsOfUse = () => {
  return (
    <div className="container mx-auto p-10 md:p-32 pt-20 lg:pt-32 py-10 text-justify">
      <h1 className="text-4xl font-bold mb-4">Terms of Use</h1>
      <p className="mb-4 mt-8">
        HUEGO HEALTHCARE Inc. and its subsidiaries and affiliates (&ldquo;HUEGO,&rdquo; &ldquo;we,&rdquo; &ldquo;our,&rdquo; or &ldquo;us&rdquo;) own and operate certain websites, including related subdomains; our mobile, tablet and other smart device applications; application program interfaces; in-store kiosks or other online services; other tools, technology and programs (collectively, the &ldquo;Platform&rdquo;) and all associated services (collectively, the &ldquo;Services&rdquo;); in each case, that reference and incorporate these Terms of Use.
      </p>
      <p className="mb-4">
        These Terms of Use (the &ldquo;Agreement&rdquo;) constitute a contract between you and us that governs your access and use of the Platform and Services. What does that mean? It means that by accessing and/or using the Platform or our Services, or by clicking a button or checking a box marked &ldquo;I Agree&rdquo; (or something similar), you agree to all the terms and conditions of this Agreement. If you do not agree, do not access and/or use the Platform or Services. As used in this Agreement, &ldquo;you&rdquo; means any visitor, user, or other person who accesses our Platform or Services, whether or not such person registered for an Account (as defined below). Unless otherwise agreed by HUEGO in a separate written agreement with you or your authorized representative, the Platform is made available solely for your personal, non-commercial use.
      </p>
      <p className="font-bold mb-2">IMPORTANT:</p>
      <p className="mb-4">
        Please review the &ldquo;DISPUTE RESOLUTION&rdquo; section set forth below carefully, as it will require you to resolve disputes with EZYMD, no matter when arising or asserted, through binding individual arbitration. You acknowledge and agree that you, by entering this agreement, expressly acknowledge that you have read and understood, and agree to be bound by, all of the terms and conditions of this agreement and have taken time to consider the consequences of this important decision.
        {/* PLEASE REVIEW THE DISPUTE RESOLUTION&rdquo; SECTION SET FORTH BELOW CAREFULLY, AS IT WILL REQUIRE YOU TO RESOLVE DISPUTES WITH EZYMD, NO MATTER WHEN ARISING OR ASSERTED, THROUGH BINDING INDIVIDUAL ARBITRATION. YOU ACKNOWLEDGE AND AGREE THAT YOU AND BY ENTERING THIS AGREEMENT, YOU EXPRESSLY ACKNOWLEDGE THAT YOU HAVE READ AND UNDERSTOOD, AND AGREE TO BE BOUND BY, ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT AND HAVE TAKEN TIME TO CONSIDER THE CONSEQUENCES OF THIS IMPORTANT DECISION. */}
      </p>
      <p className="font-bold mb-2">DISCLAIMER:</p>
      <p className="mb-4">
        The Platform, the Services, the Materials, and all other content on the Platform are provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; and without warranties of any kind, either express or implied, unless otherwise specified in writing. To the fullest extent permissible by applicable law, Huego disclaims, with respect to the Services, the Platform, the Materials, and all other content on the Platform, all warranties, express or implied, statutory or otherwise, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, and non-infringement.
        Huego does not represent or warrant that the Platform, the Services, the Materials, and/or the other content on the Platform will be secure, uninterrupted, error-free, that defects will be corrected, and/or that the Platform, the Services, the Materials, and/or other content on the Platform are free from viruses or other harmful components. Huego does not warrant or make any representations regarding the use or the results of the use of the Platform, the Services, the Materials, and/or any other content on the Platform in terms of their correctness, accuracy, reliability, timeliness, completeness, currentness, or otherwise, including, without limitation, the safety, quality, and/or timing of a delivery ordered on the Platform, and/or the food or other products delivered.
        You (and not Huego) assume the entire cost of all necessary servicing, repair, or correction relating to your use of the Platform, the Services, the Materials, and/or other content on the Platform. Applicable law may not allow the exclusion of implied warranties, so the above exclusion may not fully apply to you.
        {/* THE PLATFORM, THE SERVICES, THE MATERIALS, AND ALL OTHER CONTENT ON THE PLATFORM ARE PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; AND WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, UNLESS OTHERWISE SPECIFIED IN WRITING. TO THE FULLEST EXTENT PERMISSIBLE BY APPLICABLE LAW, HUEGO DISCLAIMS, WITH RESPECT TO THE SERVICES, THE PLATFORM, THE MATERIALS, AND ALL OTHER CONTENT ON THE PLATFORM, ALL WARRANTIES, EXPRESS OR IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. HUEGO DOES NOT REPRESENT OR WARRANT THAT THE PLATFORM, THE SERVICES, THE MATERIALS, AND/OR THE OTHER CONTENT ON THE PLATFORM WILL BE SECURE, UNINTERRUPTED, AND/OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, AND/OR THAT THE PLATFORM, THE SERVICES, THE MATERIALS, AND/OR OTHER CONTENT ON THE PLATFORM ARE FREE FROM VIRUSES OR OTHER HARMFUL COMPONENTS. HUEGO DOES NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OR THE RESULTS OF THE USE OF THE PLATFORM, THE SERVICES, THE MATERIALS, AND/OR ANY OTHER CONTENT ON THE PLATFORM IN TERMS OF THEIR CORRECTNESS, ACCURACY, RELIABILITY, TIMELINESS, COMPLETENESS, CURRENTNESS, OR OTHERWISE, INCLUDING, WITHOUT LIMITATION, THE SAFETY, QUALITY, AND/OR TIMING OF A DELIVERY ORDERED ON THE PLATFORM, AND/OR THE FOOD OR OTHER PRODUCTS DELIVERED. YOU (AND NOT HUEGO) ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR, OR CORRECTION RELATING TO YOUR USE OF THE PLATFORM, THE SERVICES, THE MATERIALS, AND/OR OTHER CONTENT ON THE PLATFORM. APPLICABLE LAW MAY NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSION MAY NOT FULLY APPLY TO YOU. */}
      </p>

      <p className="mb-4">
        HUEGO shall not be liable for delays or failures in performance resulting from causes beyond HUEGO&apos;s control, including, without limitation, delays and other problems inherent in the use of the internet and electronic communications. EZYMD is not responsible for any delays, delivery failures, or other damage resulting from such problems.
        {/* HUEGO SHALL NOT BE LIABLE FOR DELAY OR FAILURE IN PERFORMANCE RESULTING FROM CAUSES BEYOND HUEGO&apos;S CONTROL, INCLUDING, WITHOUT LIMITATION, DELAYS AND OTHER PROBLEMS INHERENT IN THE USE OF THE INTERNET AND ELECTRONIC COMMUNICATIONS. EZYMD IS NOT RESPONSIBLE FOR ANY DELAYS, DELIVERY FAILURES, OR OTHER DAMAGE RESULTING FROM SUCH PROBLEMS. */}
      </p>
      <p className="mb-4">
        HUEGO relies upon pharmacies, pharmaceuticals, and other third-party healthcare providers to provide accurate allergen and adverse effects information, as well as general product safety. HUEGO does not represent or warrant that the information accessible through the service is accurate, complete, reliable, current, or error-free. This includes, without limitation, side effects and allergen information, photos, medicine quality, descriptions, pricing, or reviews.
        All content is provided for informational purposes only. Reliance on any information provided through the service is solely at your own risk, including medical and allergen information.
        {/* HUEGO RELIES UPON PHARMACIES AND PHARMACEUTICALS AND OTHER THIRD-PARTY HEALTHCARE PROVIDERS TO PROVIDE ACCURATE ALLERGEN AND ADVERSE EFFECTS INFORMATION AND GENERAL PRODUCT SAFETY. HUEGO DOES NOT REPRESENT OR WARRANT THAT THE INFORMATION ACCESSIBLE THROUGH THE SERVICE IS ACCURATE, COMPLETE, RELIABLE, CURRENT, OR ERROR-FREE, INCLUDING, WITHOUT LIMITATION, SIDE EFFECTS AND ALLERGEN INFORMATION, PHOTOS, OR MEDICINE QUALITY, OR DESCRIPTIONS, PRICING, OR REVIEWS. ALL CONTENT IS PROVIDED FOR INFORMATIONAL PURPOSES ONLY. THE RELIANCE ON ANY INFORMATION PROVIDED THROUGH THE SERVICE IS SOLELY AT YOUR OWN RISK, INCLUDING, WITHOUT LIMITATION, MEDICAL AND ALLERGEN INFORMATION. */}
      </p>
      <p mt-2>
        Dr. Tanner Ahmed<br />
        Creator, Huego.Ai<br />
        Cofounder, Bumblebee Labs Inc
      </p>
    </div>
  );
};

export default TermsOfUse;